version: "3.8"

services:
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    environment:
      - POSTGRES_DB=canvasser_development
      - POSTGRES_USER=canvasser
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - NODE_ENV=development
      - POSTGRES_URL=postgres://canvasser@postgres:5432/canvasser_development
      - REDIS_URL=redis://redis:6379/14
    command: ["yarn", "server:dev"]
