version: "3.8"

services:
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["yarn", "server:prod"]
