version: "3.8"

services:
  redis:
    image: redis:6.2-alpine
    healthcheck:
      test: "[ $$(redis-cli ping) == 'PONG' ]"
      interval: 5s
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
