version: "3.8"

services:
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  app:
    build: .
    volumes:
      - .:/src
    ports:
      - "19000:19000"
    environment:
      - PORT=19000
